In [ ]:
import requests

data=requests.get('http://alphavaqntage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&outputsize=full&apikey=demo')

In [3]:
response=data.json()

In [7]:
len(response['Time Series (5min)'])

3584

In [5]:
x=data.data
y=data.target

In [ ]:
data.feature_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
import pandas as pd 
data=pd.DataFrame(x,columns=data.feature_names)

In [14]:
data

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [12]:
target=pd.Series(y,name='target')

In [19]:
data=pd.concat([data,target],axis=1)

In [20]:
data.to_csv('irisdata.csv')

In [ ]:
import boto3
client=boto3.client('s3')

In [27]:
client.upload_file("/Users/bootlabs/stock_price/irisdata.csv","uploaddata213","iris.csv")

In [2]:
from sklearn.datasets import load_iris
data = load_iris()

In [8]:
import pandas as pd

pd.DataFrame(response['Time Series (5min)'])

,2025-06-06 19:55:00,2025-06-06 19:50:00,2025-06-06 19:45:00,2025-06-06 19:20:00,2025-06-06 19:10:00,2025-06-06 19:00:00,2025-06-06 18:55:00,2025-06-06 18:45:00,2025-06-06 18:35:00,2025-06-06 18:30:00,...,2025-05-08 04:55:00,2025-05-08 04:50:00,2025-05-08 04:45:00,2025-05-08 04:30:00,2025-05-08 04:25:00,2025-05-08 04:20:00,2025-05-08 04:15:00,2025-05-08 04:10:00,2025-05-08 04:05:00,2025-05-08 04:00:00
1. open,268.9900,268.9900,268.9964,268.5700,268.9995,268.8700,268.5700,268.5800,268.5700,268.8700,...,254.2062,254.2162,254.1864,253.5010,253.4017,253.3520,253.1633,253.1335,253.0441,254.1864
2. high,268.9900,268.9900,268.9964,268.5700,268.9995,268.8700,268.5700,268.5800,268.7900,268.8700,...,254.7426,254.2162,254.1864,253.5010,254.2261,255.2095,253.3520,253.1335,253.0441,254.1864
3. low,268.9900,268.9900,268.9964,268.5700,268.9995,268.8700,268.5700,268.5800,268.5700,268.8700,...,254.2062,254.2062,254.1864,253.5010,253.4017,253.3520,253.1037,253.1335,253.0441,252.7064
4. close,268.9900,268.9900,268.9964,268.5700,268.9995,268.8700,268.5700,268.5800,268.5800,268.8700,...,254.4844,254.2062,254.1864,253.5010,254.2062,253.4811,253.3520,253.1335,253.0441,252.7064
5. volume,3,10,14,15,100,399917,6,13,36,399917,...,34,32,1,3,22,2875,531,1,2,33